/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DashboardReportIdRouteImport } from './routes/dashboard.$reportId'
import { Route as AdminMondayProvisionRouteImport } from './routes/admin.monday-provision'
import { Route as ReportsReportIdPrintRouteImport } from './routes/reports.$reportId.print'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportIdRoute = DashboardReportIdRouteImport.update({
  id: '/dashboard/$reportId',
  path: '/dashboard/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMondayProvisionRoute = AdminMondayProvisionRouteImport.update({
  id: '/admin/monday-provision',
  path: '/admin/monday-provision',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdPrintRoute = ReportsReportIdPrintRouteImport.update({
  id: '/reports/$reportId/print',
  path: '/reports/$reportId/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/monday-provision': typeof AdminMondayProvisionRoute
  '/dashboard/$reportId': typeof DashboardReportIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/$reportId/print': typeof ReportsReportIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/monday-provision': typeof AdminMondayProvisionRoute
  '/dashboard/$reportId': typeof DashboardReportIdRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/reports/$reportId/print': typeof ReportsReportIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin/monday-provision': typeof AdminMondayProvisionRoute
  '/dashboard/$reportId': typeof DashboardReportIdRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/reports/$reportId/print': typeof ReportsReportIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin/monday-provision'
    | '/dashboard/$reportId'
    | '/admin/'
    | '/dashboard/'
    | '/reports/'
    | '/reports/$reportId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin/monday-provision'
    | '/dashboard/$reportId'
    | '/admin'
    | '/dashboard'
    | '/reports'
    | '/reports/$reportId/print'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin/monday-provision'
    | '/dashboard/$reportId'
    | '/admin/'
    | '/dashboard/'
    | '/reports/'
    | '/reports/$reportId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminMondayProvisionRoute: typeof AdminMondayProvisionRoute
  DashboardReportIdRoute: typeof DashboardReportIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  ReportsReportIdPrintRoute: typeof ReportsReportIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$reportId': {
      id: '/dashboard/$reportId'
      path: '/dashboard/$reportId'
      fullPath: '/dashboard/$reportId'
      preLoaderRoute: typeof DashboardReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/monday-provision': {
      id: '/admin/monday-provision'
      path: '/admin/monday-provision'
      fullPath: '/admin/monday-provision'
      preLoaderRoute: typeof AdminMondayProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId/print': {
      id: '/reports/$reportId/print'
      path: '/reports/$reportId/print'
      fullPath: '/reports/$reportId/print'
      preLoaderRoute: typeof ReportsReportIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminMondayProvisionRoute: AdminMondayProvisionRoute,
  DashboardReportIdRoute: DashboardReportIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  ReportsReportIdPrintRoute: ReportsReportIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
